import argparse
import json
import os
from typing import Optional

import matplotlib.pyplot as plt
import pandas as pd


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Plot a variable from a CSV against the time column."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to the input CSV file.",
    )
    parser.add_argument(
        "--variable",
        required=True,
        help="Column name to plot.",
    )
    parser.add_argument(
        "--time-col",
        default="time",
        help="Name of the time column. Default: time",
    )
    parser.add_argument(
        "--start-time",
        type=float,
        default=None,
        help="Optional lower bound for the time axis.",
    )
    parser.add_argument(
        "--end-time",
        type=float,
        default=None,
        help="Optional upper bound for the time axis.",
    )
    parser.add_argument(
        "--rolling-window",
        type=int,
        default=None,
        help="Optional rolling mean window size for smoothing.",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=None,
        help="Optional maximum number of points to plot after filtering.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional path to save the plot. If omitted, the plot is shown.",
    )
    parser.add_argument(
        "--split-info",
        default=None,
        help="Optional JSON generated by inspect_split_ranges.py to color train/val/test segments.",
    )
    return parser


def load_and_filter_data(
    input_path: str,
    time_col: str,
    variable: str,
    start_time: Optional[float],
    end_time: Optional[float],
    max_points: Optional[int],
) -> pd.DataFrame:
    df = pd.read_csv(input_path, usecols=[time_col, variable])
    df[time_col] = pd.to_numeric(df[time_col], errors="coerce")
    df[variable] = pd.to_numeric(df[variable], errors="coerce")
    df = df.dropna(subset=[time_col, variable]).sort_values(time_col).reset_index(drop=True)

    if start_time is not None:
        df = df[df[time_col] >= start_time]
    if end_time is not None:
        df = df[df[time_col] <= end_time]

    if max_points is not None and max_points > 0 and len(df) > max_points:
        step = max(1, len(df) // max_points)
        df = df.iloc[::step].reset_index(drop=True)

    return df


def plot_variable(
    df: pd.DataFrame,
    time_col: str,
    variable: str,
    rolling_window: Optional[int],
    split_info_path: Optional[str],
    output_path: Optional[str],
) -> None:
    plt.figure(figsize=(14, 6))
    plot_df = df.copy()
    if rolling_window is not None and rolling_window > 1:
        plot_df[variable] = plot_df[variable].rolling(window=rolling_window, min_periods=1).max()

    if split_info_path:
        with open(split_info_path, "r", encoding="utf-8") as f:
            split_info = json.load(f)

        colors = {
            "train": "tab:blue",
            "val": "tab:orange",
            "test": "tab:green",
        }

        for split_name in ("train", "val", "test"):
            segments = split_info.get("splits", {}).get(split_name, [])
            for idx, segment in enumerate(segments):
                mask = (
                    (plot_df[time_col] >= segment["start_time"])
                    & (plot_df[time_col] <= segment["end_time"])
                )
                subset = plot_df.loc[mask]
                if subset.empty:
                    continue
                label = split_name if idx == 0 else None
                plt.plot(
                    subset[time_col],
                    subset[variable],
                    color=colors[split_name],
                    linewidth=1.5,
                    alpha=0.9,
                    label=label,
                )
    else:
        label = variable if rolling_window is None or rolling_window <= 1 else f"{variable} rolling max ({rolling_window})"
        plt.plot(plot_df[time_col], plot_df[variable], label=label, linewidth=1.0, alpha=0.8)

    plt.title(f"{variable} over time")
    plt.xlabel(time_col)
    plt.ylabel(variable)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    if output_path:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        plt.savefig(output_path, dpi=150)
        print(f"Plot saved to: {output_path}")
    else:
        plt.show()


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    df = load_and_filter_data(
        input_path=args.input,
        time_col=args.time_col,
        variable=args.variable,
        start_time=args.start_time,
        end_time=args.end_time,
        max_points=args.max_points,
    )

    if df.empty:
        raise ValueError("No rows left after filtering. Adjust the selected variable or time range.")

    plot_variable(
        df=df,
        time_col=args.time_col,
        variable=args.variable,
        rolling_window=args.rolling_window,
        split_info_path=args.split_info,
        output_path=args.output,
    )


if __name__ == "__main__":
    main()
